In [1]:
import pandas as pd
import numpy as np
from numpy import nan as NA
import datetime as dt
from dateutil.parser import parse
%matplotlib inline
import matplotlib.pyplot as plt
import re

In [2]:
pd.set_option('display.max_columns', None)

In [4]:
path = ''
df = pd.read_csv(path + 'Earthquake_2000_to_2023.csv')
# pd.set_option('display.min_rows', int(len(df.index)))
# df.set_index('id', inplace=True)

df.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,net,id,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2000-12-31T23:50:35.500Z,52.317,160.552,33.0,4.3,mb,14.0,NaN,NaN,1.16,us,usp000a708,2014-11-07T01:11:48.035Z,"151 km ESE of Petropavlovsk-Kamchatsky, Russia",earthquake,NaN,NaN,NaN,3.0,reviewed,us,us
1,2000-12-31T23:42:59.690Z,-26.547,-107.261,10.0,5.4,mwc,80.0,NaN,NaN,0.84,us,usp000a707,2016-11-10T00:20:01.175Z,"225 km ENE of Hanga Roa, Chile",earthquake,NaN,NaN,NaN,NaN,reviewed,us,hrv
2,2000-12-31T22:07:00.300Z,-38.530,178.930,91.0,4.0,ml,11.0,NaN,NaN,NaN,us,usp000a705,2014-11-07T01:11:48.020Z,"81 km E of Gisborne, New Zealand",earthquake,NaN,NaN,NaN,NaN,reviewed,wel,wel
3,2000-12-31T21:56:50.900Z,-38.040,178.800,33.0,5.3,mwc,58.0,NaN,NaN,NaN,us,usp000a704,2022-04-29T19:03:06.871Z,"97 km NE of Gisborne, New Zealand",earthquake,NaN,NaN,NaN,NaN,reviewed,wel,hrv
4,2000-12-31T16:12:34.400Z,-56.179,-27.217,100.0,4.5,mb,14.0,NaN,NaN,0.54,us,usp000a6zz,2014-11-07T01:11:48.004Z,South Sandwich Islands region,earthquake,NaN,NaN,NaN,2.0,reviewed,us,us

In [5]:
df.tail()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,net,id,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
321784,2022-10-10T00:54:02.984Z,52.1613,-170.4070,45.180,4.8,mwr,123.0,123.0,1.815,0.78,us,us6000isdn,2022-12-17T22:53:48.040Z,"135 km SW of Nikolski, Alaska",earthquake,7.25,5.613,0.075,17.0,reviewed,us,us
321785,2022-10-10T00:46:57.010Z,-58.7992,-24.1658,10.000,4.3,mb,12.0,179.0,8.171,0.74,us,us6000itmq,2022-12-17T22:54:09.040Z,South Sandwich Islands region,earthquake,12.14,1.924,0.168,10.0,reviewed,us,us
321786,2022-10-10T00:44:47.962Z,54.0830,-35.0767,10.000,4.6,mb,78.0,57.0,8.996,0.43,us,us6000itmh,2022-12-17T22:54:08.040Z,Reykjanes Ridge,earthquake,9.80,1.871,0.071,59.0,reviewed,us,us
321787,2022-10-10T00:26:17.442Z,38.8416,142.1723,45.627,4.6,mwr,118.0,122.0,2.124,0.55,us,us6000isdk,2022-12-17T22:53:48.040Z,"47 km ESE of ?funato, Japan",earthquake,7.96,5.771,0.063,24.0,reviewed,us,us
321788,2022-10-10T00:02:59.585Z,42.0966,144.1664,35.000,4.9,mb,143.0,74.0,0.756,0.58,us,us6000isdf,2022-12-17T22:53:48.040Z,"Hokkaido, Japan region",earthquake,3.78,1.824,0.044,160.0,reviewed,us,us

In [6]:
df.shape

(321789, 22)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 321789 entries, 0 to 321788
Data columns (total 22 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   time             321789 non-null  object
 1   latitude         321789 non-null  float64
 2   longitude        321789 non-null  float64
 3   depth            321789 non-null  float64
 4   mag              321789 non-null  float64
 5   magType          321789 non-null  object
 6   nst              185681 non-null  float64
 7   gap              286434 non-null  float64
 8   dmin             150241 non-null  float64
 9   rms              301990 non-null  float64
 10  net              321789 non-null  object
 11  id               321789 non-null  object
 12  updated          321789 non-null  object
 13  place            319870 non-null  object
 14  type             321789 non-null  object
 15  horizontalError  136798 non-null  float64
 16  depthError       215716 non-null  float64
 17  magError         149854 non-null  float64
 18  magNst           275295 non-null  float64
 19  status           321789 non-null  object
 20  locationSource   321789 non-null  object
 21  magSource        321789 non-null  object
dtypes: float64(12), object(10)
memory usage: 54.0+ MB

In [9]:
df.describe()

,latitude,longitude,depth,mag,nst,gap,dmin,rms,horizontalError,depthError,magError,magNst
count,321789.000000,321789.000000,321789.000000,321789.000000,185681.000000,286434.000000,150241.000000,301990.000000,136798.000000,215716.000000,149854.000000,275295.000000
mean,3.790758,38.417872,79.594908,4.536560,55.856313,112.002455,3.898871,0.873939,8.596409,9.630159,0.128768,28.063746
std,29.099115,120.665175,129.250402,0.420547,76.136256,52.375836,5.040551,0.302056,3.554687,795.508198,0.071220,48.633972
min,-84.422000,-179.999700,-3.290000,3.380000,0.000000,6.500000,0.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000
25%,-18.020600,-72.032000,10.000000,4.200000,16.000000,73.000000,1.193000,0.690000,6.200000,1.900000,0.078000,6.000000
50%,0.859000,95.086500,33.000000,4.500000,29.000000,108.000000,2.443000,0.870000,8.200000,5.800000,0.118000,13.000000
75%,28.157400,141.746000,77.300000,4.700000,61.000000,141.000000,4.509000,1.050000,10.700000,9.300000,0.162000,29.000000
max,87.386000,180.000000,735.800000,9.100000,934.000000,358.300000,64.498000,69.320000,99.000000,367558.100000,1.680000,941.000000

In [12]:
df.isnull().sum()

# df.place = (df.place.str).extract('(, .+$)').replace(',', '').replace('( $|^ )') # not working as intended
# df

time                    0
latitude                0
longitude               0
depth                   0
mag                     0
magType                 0
nst                136108
gap                 35355
dmin               171548
rms                 19799
net                     0
id                      0
updated                 0
place                1919
type                    0
horizontalError    184991
depthError         106073
magError           171935
magNst              46494
status                  0
locationSource          0
magSource               0
dtype: int64

In [6]:
(df.gap.isnull().sum())/(len(df.gap))*100

10.987013229165695

In [7]:
# Drop duplicates
before=len(df.index)
print(f"BEFORE: {before}")
df.drop_duplicates(inplace=True)
after=len(df.index)
print(f"AFTER: {after}")
print(f"REMOVED: {before-after}")


# print(df[((df.gap > 180) | (df.dmin >= 10)) & (df.mag < 5.5)].drop_duplicates().id.count())
# gap > 180 or dmin >= 10 with a mag < 5.5

# df.drop()

BEFORE: 321789
AFTER: 321360
REMOVED: 429

In [8]:
# Drop rows with mag lower than 4
before=len(df.index)
print(f"BEFORE: {before}")
df.drop(df[df.mag<=4].index, inplace=True)
after=len(df.index)
print(f"AFTER: {after}")
print(f"REMOVED: {before-after}")

BEFORE: 321360
AFTER: 300188
REMOVED: 21172

In [9]:
# Replace 0 or NA nst values with 1
print("BEFORE")
print(df.nst[df.nst == 0].count())
print(df.nst[df.nst.isnull()].count())

# change 0 to 1
df.nst.replace(0,1, inplace=True)

print("AFTER")
print(df.nst[df.nst == 0].count())
print(df.nst[df.nst.isnull()].count())

BEFORE
13
0
AFTER
0
0

In [10]:
# Replace NA in magerror with 0
print(f"BEFORE (magError.isnull()): {len(df.magError[df.magError.isnull()])}")
df.magError.replace(NA,0,inplace=True)
print(f"AFTER  (magError.isnull()): {len(df.magError[df.magError.isnull()])}")

print(f"BEFORE (magNst.isnull() or 0): {len(df.magNst[(df.magNst.isnull()) | (df.magNst == 0)])}")
df.magNst.replace(NA,1,inplace=True)
df.magNst.replace(0,1,inplace=True)
print(f"AFTER  (magNst.isnull() or 0): {len(df.magNst[(df.magNst.isnull()) | (df.magNst == 0)])}")

BEFORE (magError.isnull()): 158317
AFTER  (magError.isnull()): 0
BEFORE (magNst.isnull() or 0): 41293
AFTER  (magNst.isnull() or 0): 0

In [11]:
print(f"BEFORE: {len(df.index)}")
print(f"DROPPED (gap) : {len(df[(df.gap > 180) & (df.mag < 5.5)].index)}")
df.drop(df[(df.gap > 180) & (df.mag < 5.5)].index, inplace=True)
print(f"DROPPED (dmin): {len(df[(df.dmin >= 10) & (df.mag < 5.5)].index)}")
df.drop(df[(df.dmin >= 10) & (df.mag < 5.5)].index, inplace=True)
print(f"AFTER: {len(df.index)}")

# print(df[((df.gap > 180) | (df.dmin >= 10)) & (df.mag < 5.5)].drop_duplicates().id.count())
# gap > 180 or dmin >= 10 with a mag < 5.5

# df.drop()

BEFORE: 300188
DROPPED (gap) : 26390
DROPPED (dmin): 8907
AFTER: 264891

In [12]:
df.time = df.time.map(lambda x: parse(x))
df.updated = df.updated.map(lambda x: parse(x))

In [13]:
df.insert(0,'time2',pd.PeriodIndex(time=df.time))
df

TypeError: __new__() got an unexpected keyword argument time

In [12]:
# Commencing E.D.A.
df.describe()

len(df[df.mag>=7].index)/len(df.index)*100

0.13514992959368194

In [13]:
# only 0.135% of all earthquakes in the dataset are mag 7.0 or higher :|

import geopandas as gpd
countries = gpd.read_file(
               gpd.datasets.get_path("naturalearth_lowres"))
# countries.head()

In [17]:
df.corr()

C:\Users\prana\AppData\Local\Temp\ipykernel_9380\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

,latitude,longitude,depth,mag,nst,gap,dmin,rms,horizontalError,depthError,magError,magNst
latitude,1.000000,0.246419,-0.189765,-0.098773,0.167654,0.029405,-0.232896,-0.022451,-0.272426,0.004276,-0.090449,0.118957
longitude,0.246419,1.000000,-0.209889,0.003501,-0.046940,-0.020766,-0.044991,-0.030247,-0.062505,0.003076,-0.022776,-0.059962
depth,-0.189765,-0.209889,1.000000,-0.110880,0.022419,-0.033043,0.125282,-0.104391,0.440848,0.000501,0.033717,0.080924
mag,-0.098773,0.003501,-0.110880,1.000000,0.690228,-0.479150,0.124033,0.087537,-0.129915,-0.000774,-0.258526,0.156194
nst,0.167654,-0.046940,0.022419,0.690228,1.000000,-0.517784,-0.001100,-0.034943,-0.197167,-0.254654,-0.093306,0.271560
gap,0.029405,-0.020766,-0.033043,-0.479150,-0.517784,1.000000,-0.012893,-0.029039,0.266603,0.217544,0.125645,-0.197452
dmin,-0.232896,-0.044991,0.125282,0.124033,-0.001100,-0.012893,1.000000,-0.044995,0.428922,-0.034003,-0.044107,-0.009929
rms,-0.022451,-0.030247,-0.104391,0.087537,-0.034943,-0.029039,-0.044995,1.000000,-0.094930,0.000244,-0.266478,-0.090874
horizontalError,-0.272426,-0.062505,0.440848,-0.129915,-0.197167,0.266603,0.428922,-0.094930,1.000000,0.314137,0.120170,-0.083559
depthError,0.004276,0.003076,0.000501,-0.000774,-0.254654,0.217544,-0.034003,0.000244,0.314137,1.000000,-0.005307,-0.003140
magError,-0.090449,-0.022776,0.033717,-0.258526,-0.093306,0.125645,-0.044107,-0.266478,0.120170,-0.005307,1.000000,-0.031181
magNst,0.118957,-0.059962,0.080924,0.156194,0.271560,-0.197452,-0.009929,-0.090874,-0.083559,-0.003140,-0.031181,1.000000

In [29]:
bins = [4.0,5.0,6.0,7.0,8.0,9.0,10.0]
df['mag_bins'] = pd.cut(df.mag, bins)
df

df['mag_bins']=pd.qcut(df.mag,5)
df

df['mag_bins']=pd.get_dummies(df.mag)
df

ValueError: Columns must be same length as key