In [1]:
import pandas as pd
import numpy as np
from numpy import nan as NA
import datetime as dt
from dateutil.parser import parse
%matplotlib inline
import matplotlib.pyplot as plt
import re

In [2]:
path = ''
df = pd.read_csv(path + 'Earthquake_2000_to_2023.csv')

df.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2000-12-31T23:50:35.500Z,52.317,160.552,33.0,4.3,mb,14.0,NaN,NaN,1.16,...,2014-11-07T01:11:48.035Z,"151 km ESE of Petropavlovsk-Kamchatsky, Russia",earthquake,NaN,NaN,NaN,3.0,reviewed,us,us
1,2000-12-31T23:42:59.690Z,-26.547,-107.261,10.0,5.4,mwc,80.0,NaN,NaN,0.84,...,2016-11-10T00:20:01.175Z,"225 km ENE of Hanga Roa, Chile",earthquake,NaN,NaN,NaN,NaN,reviewed,us,hrv
2,2000-12-31T22:07:00.300Z,-38.530,178.930,91.0,4.0,ml,11.0,NaN,NaN,NaN,...,2014-11-07T01:11:48.020Z,"81 km E of Gisborne, New Zealand",earthquake,NaN,NaN,NaN,NaN,reviewed,wel,wel
3,2000-12-31T21:56:50.900Z,-38.040,178.800,33.0,5.3,mwc,58.0,NaN,NaN,NaN,...,2022-04-29T19:03:06.871Z,"97 km NE of Gisborne, New Zealand",earthquake,NaN,NaN,NaN,NaN,reviewed,wel,hrv
4,2000-12-31T16:12:34.400Z,-56.179,-27.217,100.0,4.5,mb,14.0,NaN,NaN,0.54,...,2014-11-07T01:11:48.004Z,South Sandwich Islands region,earthquake,NaN,NaN,NaN,2.0,reviewed,us,us

In [3]:
df.tail()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
321784,2022-10-10T00:54:02.984Z,52.1613,-170.4070,45.180,4.8,mwr,123.0,123.0,1.815,0.78,...,2022-12-17T22:53:48.040Z,"135 km SW of Nikolski, Alaska",earthquake,7.25,5.613,0.075,17.0,reviewed,us,us
321785,2022-10-10T00:46:57.010Z,-58.7992,-24.1658,10.000,4.3,mb,12.0,179.0,8.171,0.74,...,2022-12-17T22:54:09.040Z,South Sandwich Islands region,earthquake,12.14,1.924,0.168,10.0,reviewed,us,us
321786,2022-10-10T00:44:47.962Z,54.0830,-35.0767,10.000,4.6,mb,78.0,57.0,8.996,0.43,...,2022-12-17T22:54:08.040Z,Reykjanes Ridge,earthquake,9.80,1.871,0.071,59.0,reviewed,us,us
321787,2022-10-10T00:26:17.442Z,38.8416,142.1723,45.627,4.6,mwr,118.0,122.0,2.124,0.55,...,2022-12-17T22:53:48.040Z,"47 km ESE of ?funato, Japan",earthquake,7.96,5.771,0.063,24.0,reviewed,us,us
321788,2022-10-10T00:02:59.585Z,42.0966,144.1664,35.000,4.9,mb,143.0,74.0,0.756,0.58,...,2022-12-17T22:53:48.040Z,"Hokkaido, Japan region",earthquake,3.78,1.824,0.044,160.0,reviewed,us,us

In [4]:
df.shape

(321789, 22)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 321789 entries, 0 to 321788
Data columns (total 22 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   time             321789 non-null  object
 1   latitude         321789 non-null  float64
 2   longitude        321789 non-null  float64
 3   depth            321789 non-null  float64
 4   mag              321789 non-null  float64
 5   magType          321789 non-null  object
 6   nst              185681 non-null  float64
 7   gap              286434 non-null  float64
 8   dmin             150241 non-null  float64
 9   rms              301990 non-null  float64
 10  net              321789 non-null  object
 11  id               321789 non-null  object
 12  updated          321789 non-null  object
 13  place            319870 non-null  object
 14  type             321789 non-null  object
 15  horizontalError  136798 non-null  float64
 16  depthError       215716 non-null  float64
 17  magError         149854 non-null  float64
 18  magNst           275295 non-null  float64
 19  status           321789 non-null  object
 20  locationSource   321789 non-null  object
 21  magSource        321789 non-null  object
dtypes: float64(12), object(10)
memory usage: 54.0+ MB

In [6]:
df.describe()

,latitude,longitude,depth,mag,nst,gap,dmin,rms,horizontalError,depthError,magError,magNst
count,321789.000000,321789.000000,321789.000000,321789.000000,185681.000000,286434.000000,150241.000000,301990.000000,136798.000000,215716.000000,149854.000000,275295.000000
mean,3.790758,38.417872,79.594908,4.536560,55.856313,112.002455,3.898871,0.873939,8.596409,9.630159,0.128768,28.063746
std,29.099115,120.665175,129.250402,0.420547,76.136256,52.375836,5.040551,0.302056,3.554687,795.508198,0.071220,48.633972
min,-84.422000,-179.999700,-3.290000,3.380000,0.000000,6.500000,0.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000
25%,-18.020600,-72.032000,10.000000,4.200000,16.000000,73.000000,1.193000,0.690000,6.200000,1.900000,0.078000,6.000000
50%,0.859000,95.086500,33.000000,4.500000,29.000000,108.000000,2.443000,0.870000,8.200000,5.800000,0.118000,13.000000
75%,28.157400,141.746000,77.300000,4.700000,61.000000,141.000000,4.509000,1.050000,10.700000,9.300000,0.162000,29.000000
max,87.386000,180.000000,735.800000,9.100000,934.000000,358.300000,64.498000,69.320000,99.000000,367558.100000,1.680000,941.000000

In [7]:
df.isnull().sum()

time                    0
latitude                0
longitude               0
depth                   0
mag                     0
magType                 0
nst                136108
gap                 35355
dmin               171548
rms                 19799
net                     0
id                      0
updated                 0
place                1919
type                    0
horizontalError    184991
depthError         106073
magError           171935
magNst              46494
status                  0
locationSource          0
magSource               0
dtype: int64

In [8]:
(df.isnull().sum())/(df.shape[0])*100

time                0.000000
latitude            0.000000
longitude           0.000000
depth               0.000000
mag                 0.000000
magType             0.000000
nst                42.297282
gap                10.987013
dmin               53.310710
rms                 6.152790
net                 0.000000
id                  0.000000
updated             0.000000
place               0.596354
type                0.000000
horizontalError    57.488292
depthError         32.963526
magError           53.430975
magNst             14.448598
status              0.000000
locationSource      0.000000
magSource           0.000000
dtype: float64

<h2>Data Cleaning</h2>

<h3>Filtering - </h3>

In [9]:
# Drop duplicates
before=len(df.index)
print(f"BEFORE: {before}")
df.drop_duplicates(inplace=True)
after=len(df.index)
print(f"AFTER: {after}")
print(f"REMOVED: {before-after}")

BEFORE: 321789
AFTER: 321360
REMOVED: 429

In [10]:
# Drop rows with mag lower than 4
before=len(df.index)
print(f"BEFORE: {before}")
df.drop(df[df.mag<=4].index, inplace=True)
after=len(df.index)
print(f"AFTER: {after}")
print(f"REMOVED: {before-after}")

BEFORE: 321360
AFTER: 300188
REMOVED: 21172

In [11]:
print(f"BEFORE: {len(df.index)}")
print(f"DROPPED (gap) : {len(df[(df.gap > 180) & (df.mag < 5.5)].index)}")
df.drop(df[(df.gap > 180) & (df.mag < 5.5)].index, inplace=True)
print(f"DROPPED (dmin): {len(df[(df.dmin >= 10) & (df.mag < 5.5)].index)}")
df.drop(df[(df.dmin >= 10) & (df.mag < 5.5)].index, inplace=True)
print(f"AFTER: {len(df.index)}")

# print(df[((df.gap > 180) | (df.dmin >= 10)) & (df.mag < 5.5)].drop_duplicates().id.count())
# gap > 180 or dmin >= 10 with a mag < 5.5

# df.drop()

BEFORE: 300188
DROPPED (gap) : 26390
DROPPED (dmin): 8907
AFTER: 264891

In [12]:
# This is to manipulate the string values in PLACE COLUMN = 

# df.place = (df.place.str).extract('(, .+$)').replace(',', '').replace('( $|^ )') # not working as intended
# df

<h2>Imputing - </h2>

<p> Imputing nst null and zero values with 1.<br>
As there has to be a minimum of one station that reported the magnitude. </p>

In [13]:
# Using fillna(1) method to replace NaN (null) values with 1.
# Using replace(0, 1) method to replace any zero values with 1.

df['nst'] = df['nst'].fillna(1).replace(0, 1)

<p>Replace NA (null) values in the 'magError' column with 0.</p>

In [14]:
# Using the fillna(0) method to replace NA values in the 'magError' column with 0.

df['magError'].fillna(0, inplace = True)

<p>To handle the null values in the 'gap' column, we fill them with the median value. <br>
This approach is neutral and doesn't bias the data.</p>

In [15]:
# Using the fillna() method with inplace=True to replace null values in 'gap' with the median of the gap column.

df['gap'].fillna(df['gap'].median(), inplace=True)

In [16]:
distinct_magType = df['magType'].unique()
print('Distinct Values in the magType Column - ', distinct_magType)
print(f'The number of distinct magnitude types in the column magType = {len(distinct_magType)}')

Distinct Values in the magType Column -  ['mb' 'mwc' 'ml' 'md' 'mwb' 'mw' 'ms' 'mblg' 'mwr' 'mww' 'mlg' 'm' 'mh'
 'mc' 'Mb' 'Md' 'mb_lg' 'Ml' 'ms_20' 'mlr' 'mwp' 'mlv' 'Mi']
The number of distinct magnitude types in the column magType = 23

<p>
Here we have 23 distinct values in the magType column.<br>
To simplify the dataset for analysis,<br> 
We can create broader categories that group the magnitude types based on their method of calculation or the type of seismic waves they measure.<br><br>
Body Wave Magnitudes:<br>
Category Name: "body wave"<br>
Includes: mb, Mb, mb_lg, mblg<br>

Surface Wave Magnitudes:<br>
Category Name: "surface wave"<br>
Includes: ms, ms_20<br>
    
Moment Magnitudes:<br>
Category Name: "moment"<br>
Includes: mw, mwc, mwb, mwr, mww, mwp, ml, Ml, mlg<br>

Duration Magnitudes:<br>
Category Name: "duration"<br>
Includes: md, Md, m, mh, mc, mlr, mlv, Mi<br>

</p>

In [17]:
# Define the translation dictionary
magType_categories = {
    'body wave': ['mb', 'Mb', 'mb_lg', 'mblg'],
    'surface wave': ['ms', 'ms_20'],
    'moment': ['mw', 'mwc', 'mwb', 'mwr', 'mww', 'mwp', 'ml', 'Ml', 'mlg'], 
    'duration': ['md', 'Md', 'm', 'mh', 'mc', 'mlr', 'mlv', 'Mi']
}
# Function to replace values in a column with the corresponding key from the dictionary
def replace_with_category(magType, magTypeDict):
    for category, values in magTypeDict.items():
        if magType in values:
            return category
    return magType

# Assuming 'df' is your DataFrame and 'magType' is the column you want to update
df['magType'] = df['magType'].apply(lambda magType: replace_with_category(magType, magType_categories))

In [18]:
df['magType'].value_counts()

body wave       221000
moment           40256
duration          3441
surface wave       194
Name: magType, dtype: int64

<h2> Correlation Analysis - </h2>

In [19]:
df.corr(numeric_only=True)

,latitude,longitude,depth,mag,nst,gap,dmin,rms,horizontalError,depthError,magError,magNst
latitude,1.000000,0.246419,-0.189765,-0.098773,0.127879,0.027491,-0.232896,-0.022451,-0.272426,0.004276,-0.090449,0.136867
longitude,0.246419,1.000000,-0.209889,0.003501,-0.007144,-0.019579,-0.044991,-0.030247,-0.062505,0.003076,-0.022776,-0.082103
depth,-0.189765,-0.209889,1.000000,-0.110880,-0.014238,-0.031313,0.125282,-0.104391,0.440848,0.000501,0.033717,0.070262
mag,-0.098773,0.003501,-0.110880,1.000000,0.515857,-0.446304,0.124033,0.087537,-0.129915,-0.000774,-0.258526,0.334880
nst,0.127879,-0.007144,-0.014238,0.515857,1.000000,-0.312544,-0.020835,0.052655,-0.094033,-0.000987,-0.322202,0.221081
gap,0.027491,-0.019579,-0.031313,-0.446304,-0.312544,1.000000,-0.012893,-0.026103,0.264310,0.001843,0.118310,-0.269047
dmin,-0.232896,-0.044991,0.125282,0.124033,-0.020835,-0.012893,1.000000,-0.044995,0.428922,-0.034003,-0.044107,-0.005452
rms,-0.022451,-0.030247,-0.104391,0.087537,0.052655,-0.026103,-0.044995,1.000000,-0.094930,0.000244,-0.266478,-0.077271
horizontalError,-0.272426,-0.062505,0.440848,-0.129915,-0.094033,0.264310,0.428922,-0.094930,1.000000,0.314137,0.120170,-0.093588
depthError,0.004276,0.003076,0.000501,-0.000774,-0.000987,0.001843,-0.034003,0.000244,0.314137,1.000000,-0.005307,-0.191870
magError,-0.090449,-0.022776,0.033717,-0.258526,-0.322202,0.118310,-0.044107,-0.266478,0.120170,-0.005307,1.000000,-0.080904
magNst,0.136867,-0.082103,0.070262,0.334880,0.221081,-0.269047,-0.005452,-0.077271,-0.093588,-0.191870,-0.080904,1.000000

<h3> Analysis: </h3>
<li>
Magnitude and Number of Stations (nst):<br>
There is a moderately strong positive correlation between mag (magnitude) and nst (number of stations reporting the earthquake). This suggests that larger earthquakes tend to be recorded by more seismic stations, which is expected since larger quakes are likely to be detected by a broader network.
<br>
<li>Magnitude and Gap:<br>
mag has a moderate negative correlation with gap. This indicates that as the magnitude of an earthquake increases, the gap (largest azimuthal gap between adjacent stations) tends to decrease. This could be due to larger earthquakes being more likely to have comprehensive coverage by seismic networks.
<br>
<li>Depth and Horizontal Error:<br>
There is a moderate positive correlation between depth and horizontalError. This might suggest that as the depth of an earthquake increases, the uncertainty in the horizontal positioning also increases, possibly due to the increased complexity in accurately locating deeper seismic events.
<br>
<li>Magnitude and Magnitude Error (magError):<br>
The correlation between mag and magError is moderately negative. Higher magnitudes might have a smaller reported error, potentially because they are easier to estimate accurately due to stronger seismic signals.
<br>
<li>Number of Stations (nst) and Gap:<br>
There's a strong negative correlation between nst and gap. More stations contributing to an earthquake report can result in a smaller gap, indicating a higher confidence in the earthquake's reported location.
<br>
<li>Dmin and Horizontal Error:<br>
dmin (the horizontal distance to the nearest station from the epicenter) has a strong positive correlation with horizontalError. The further the nearest station is, the greater the uncertainty in the earthquake's horizontal position, which makes sense because more distant stations would likely lead to less precise location measurements.
<br>
<li>Horizontal Error and Depth Error:<br>
There is a positive correlation between horizontalError and depthError, suggesting that when there's more uncertainty in the horizontal location of an earthquake, there tends to be more uncertainty in the depth measurement as well.
    
</li>

<h2> E.D.A. after Data Cleaning - </h3>

<h2> Data Analysis </h2>

In [20]:
# Parse string to datetime format - 

#df.time = df.time.map(lambda x: parse(x))
#df.updated = df.updated.map(lambda x: parse(x))

#df.insert(0,'time2',pd.PeriodIndex(time=df.time))
#df

<h2> Data Visualization</h2>